Repository Recruiting-Your-Club/ryc, pull requests merged in 2025-05, with the labels that each got.

#163 [FE] 메인페이지 구현
  client/src/assets/images/banner.png
  client/src/components/Header/Header.style.ts
  client/src/components/Header/Header.tsx
  client/src/components/MainCard/MainCard.style.tsx
  client/src/components/MainCard/MainCard.tsx
  client/src/components/MainCard/index.tsx
  client/src/components/MainCard/types.ts
  client/src/components/index.tsx
  client/src/layouts/UserLayout/UserLayout.styles.ts
  client/src/layouts/UserLayout/UserLayout.tsx
  client/src/pages/MainPage/MainPage.style.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/index.tsx
  client/src/pages/MainPage/types.ts
  client/src/pages/TestPage/index.tsx
  client/src/pages/index.tsx
  client/src/router.tsx
  client/src/styles/theme/breakPoint.ts
  client/src/styles/theme/index.ts
  client/src/types/styles/theme.d.ts
Labels: ⭐️ feature, 🚀FE

#161 [Refactor] Calendar 컴포넌트 리팩토링
  client/src/components/_common/Calendar/Calendar.tsx
  client/src/components/_common/Calendar/CalendarStyle.tsx
  client/src/components/_common/Calendar/types.ts
  client/src/components/_common/Calendar/useCalendar.ts
  client/src/constants/calendar.ts
Labels: 🔨 refactor, 🚀FE

#165 [FE] Footer 구현
  client/src/components/Footer/Footer.stories.tsx
  client/src/components/Footer/Footer.style.ts
  client/src/components/Footer/Footer.tsx
  client/src/components/Footer/index.tsx
  client/src/layouts/ManagerLayout/ManagerLayout.tsx
  client/src/layouts/UserLayout/UserLayout.tsx
  client/src/styles/global.ts
Labels: ⭐️ feature, 🚀FE

#171 [FE] 클럽 상세조회 페이지 작성
  client/src/components/ClubBox/ClubBox.style.ts
  client/src/components/ClubBox/ClubBox.tsx
  client/src/components/ClubBox/index.tsx
  client/src/components/ClubNavigation/ClubNavigation.style.ts
  client/src/components/ClubNavigation/ClubNavigation.tsx
  client/src/components/ClubNavigation/index.tsx
  client/src/components/ClubNavigation/types.ts
  client/src/components/Header/Header.style.ts
  client/src/components/ImageDialog/ImageDialog.style.tsx
  client/src/components/ImageDialog/ImageDialog.tsx
  client/src/components/ImageDialog/index.tsx
  client/src/components/ImageDialog/types.ts
  client/src/components/RecruitCard/RecruitCard.style.tsx
  client/src/components/RecruitCard/RecruitCard.tsx
  client/src/components/RecruitCard/index.tsx
  client/src/components/RecruitCard/types.ts
  client/src/components/_common/Dialog/types.ts
  client/src/components/_common/Image/Image.style.tsx
  client/src/components/_common/Image/Image.tsx
  client/src/components/_common/Image/index.tsx
  client/src/components/_common/index.tsx
  client/src/components/index.tsx
  client/src/hooks/useDialog.tsx
  client/src/layouts/UserLayout/UserLayout.styles.ts
  client/src/layouts/UserLayout/UserLayout.tsx
  client/src/pages/ClubDetailPage/ClubDetailPage.style.ts
  client/src/pages/ClubDetailPage/ClubDetailPage.tsx
  client/src/pages/ClubDetailPage/ClubIntroPage/ClubIntro.style.ts
  client/src/pages/ClubDetailPage/ClubIntroPage/ClubIntroPage.tsx
  client/src/pages/ClubDetailPage/ClubIntroPage/index.tsx
  client/src/pages/ClubDetailPage/RecruitmentPage/RecruitmentPage.style.ts
  client/src/pages/ClubDetailPage/RecruitmentPage/RecruitmentPage.tsx
  client/src/pages/ClubDetailPage/RecruitmentPage/index.tsx
  client/src/pages/ClubDetailPage/index.tsx
  client/src/pages/MainPage/MainPage.style.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/TestPage/index.tsx
  client/src/pages/index.tsx
  client/src/router.tsx
  client/src/styles/global.ts
Labels: ⭐️ feature, 🚀FE

#184 [FE] 모집공고 카드 눌렀을 때 나오는 Dialog, Page 구현
  client/src/components/ClubBox/ClubBox.style.ts
  client/src/components/ClubNavigation/ClubNavigation.style.ts
  client/src/components/ClubNavigation/ClubNavigation.tsx
  client/src/components/ClubNavigation/types.ts
  client/src/components/Header/Header.style.ts
  client/src/components/MainCard/MainCard.tsx
  client/src/components/RecruitCard/RecruitCard.tsx
  client/src/components/RecruitCard/types.ts
  client/src/components/RecruitDialog/RecruitDialog.style.tsx
  client/src/components/RecruitDialog/RecruitDialog.tsx
  client/src/components/RecruitDialog/index.tsx
  client/src/components/RecruitDialog/types.ts
  client/src/components/_common/Dialog/Dialog.tsx
  client/src/components/index.tsx
  client/src/layouts/ManagerLayout/ManagerLayout.tsx
  client/src/layouts/UserLayout/UserLayout.tsx
  client/src/pages/ClubDetailPage/ClubDetailPage.style.ts
  client/src/pages/ClubDetailPage/ClubDetailPage.tsx
  client/src/pages/ClubDetailPage/ClubIntroPage/ClubIntro.style.ts
  client/src/pages/ClubDetailPage/RecruitmentPage/RecruitmentPage.style.ts
  client/src/pages/ClubDetailPage/RecruitmentPage/RecruitmentPage.tsx
  client/src/pages/MainPage/MainPage.style.ts
  client/src/pages/RecruitmentPage/RecruitmentPage.style.tsx
  client/src/pages/RecruitmentPage/RecruitmentPage.tsx
  client/src/pages/RecruitmentPage/index.tsx
  client/src/pages/index.tsx
  client/src/router.tsx
Labels: ⭐️ feature, 🚀FE

#187 [REFACTOR/FE] Footer 리팩토링
  client/src/components/Footer/Footer.style.ts
  client/src/components/Footer/Footer.tsx
  client/src/pages/TestPage/index.tsx
Labels: 🔨 refactor, 🚀FE

#205 [REFACTOR/FE] FileUpLoader import 경로 수정
  client/src/hooks/components/useFilteredFile.tsx
Labels: 🚀FE
