Repository Recruiting-Your-Club/ryc, pull requests merged in 2025-09, with the labels that each got.

#541 [FE] UI 개선
  monorepo/apps/admin/src/components/ErrorDialog/ErrorDialog.tsx
  monorepo/apps/admin/src/components/InterviewTimeTable/InterviewTimeTable.tsx
  monorepo/apps/admin/src/constants/errorText.ts
  monorepo/apps/admin/src/pages/AnnouncementPage/PersonalQuestionPage/PersonalQuestion.style.ts
  monorepo/apps/admin/src/pages/AnnouncementPage/PersonalQuestionPage/PersonalQuestionPage.tsx
  monorepo/apps/admin/src/pages/ErrorFallbackPage/ErrorFallbackPage.tsx
  monorepo/apps/admin/src/pages/InterviewEvaluationPage/InterviewEvaluationPage.tsx
  monorepo/apps/user/src/components/ErrorDialog/ErrorDialog.tsx
  monorepo/apps/user/src/constants/errorText.ts
  monorepo/apps/user/src/pages/ErrorFallbackPage/ErrorFallbackPage.tsx
  monorepo/apps/user/src/pages/ReservationPage/ReservationPage.tsx
Labels: 🔨 refactor, 🚀FE

#547 [FE] 이메일 전송 실패 시 처리 방법 수정
  monorepo/apps/admin/src/components/InterviewSettingDialog/InterviewSettingDialog.tsx
  monorepo/apps/admin/src/components/InterviewSettingDialog/types.ts
  monorepo/apps/admin/src/components/PlainEmailDialog/PlainEmailDialog.tsx
  monorepo/apps/admin/src/components/PlainEmailDialog/types.ts
  monorepo/apps/admin/src/pages/StepManagementPage/StepManagementPage.tsx
Labels: 🐛 bug, 🚀FE

#552 [FE/HOTFIX] 사이드바에서 동아리 생성 페이지로의 이동 제한
  monorepo/apps/admin/src/components/SideBar/SideBar.tsx
Labels: 🐛 bug, 🚀FE

#553 [FE] 면접 일정 관리 페이지 내 Dialog 확인 단계 추가
  monorepo/apps/admin/src/components/InterviewTimeTable/InterviewTimeTable.tsx
  monorepo/apps/admin/src/pages/ApplicantSchedulePage/ApplicantSchedulePage.tsx
Labels: 🔨 refactor, 🚀FE

#559 [BE] 면접 타임대(슬롯) 생성/예약/변경 중복 제한 및 면접 타임대 정렬 후 데이터 제공으로 수정
  server/src/main/java/com/ryc/api/v2/common/exception/code/InterviewErrorCode.java
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewRepository.java
  server/src/main/java/com/ryc/api/v2/interview/infra/InterviewRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/interview/infra/jpa/InterviewReservationJpaRepository.java
  server/src/main/java/com/ryc/api/v2/interview/service/InterviewService.java
Labels: 🐛 bug, 💻 BE

#561 [FE/HOTFIX] 프론트 공고 요약 버그 수정
  monorepo/apps/admin/public/index.html
  monorepo/apps/admin/src/pages/AnnouncementPage/RecruitmenPage/RecruitmentPage.tsx
  monorepo/apps/user/public/index.html
  monorepo/apps/user/src/utils/parseAnnouncementData.ts
Labels: 🐛 bug, 🚀FE

#564 [FE] ErrorBoundary reset 방식 변경
  monorepo/apps/admin/src/pages/ErrorBoundaryWrapperPage/ErrorBoundaryWrapperPage.tsx
  monorepo/apps/admin/src/pages/ErrorBoundaryWrapperPage/index.ts
  monorepo/apps/admin/src/pages/index.ts
  monorepo/apps/admin/src/router.tsx
  monorepo/apps/user/src/components/ErrorDialog/ErrorDialog.tsx
  monorepo/apps/user/src/pages/ErrorBoundaryWrapperPage/ErrorBoundaryWrapperPage.tsx
  monorepo/apps/user/src/pages/ErrorBoundaryWrapperPage/index.ts
  monorepo/apps/user/src/pages/ErrorFallbackPage/ErrorFallbackPage.tsx
  monorepo/apps/user/src/pages/index.ts
  monorepo/apps/user/src/router.tsx
Labels: 🔨 refactor, 🚀FE

#574 [BE] 면접 도메인 API 수정
  server/build.gradle
  server/src/main/java/com/ryc/api/v2/common/dispatch/EmailSenderService.java
  server/src/main/java/com/ryc/api/v2/common/exception/code/InterviewErrorCode.java
  server/src/main/java/com/ryc/api/v2/email/domain/EmailValidator.java
  server/src/main/java/com/ryc/api/v2/email/domain/event/InterviewReminderEvent.java
  server/src/main/java/com/ryc/api/v2/email/domain/event/InterviewSlotEmailEvent.java
  server/src/main/java/com/ryc/api/v2/email/presentation/EmailHttpApi.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/request/EmailSendRequest.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/request/InterviewSlotEmailSendRequest.java
  server/src/main/java/com/ryc/api/v2/email/service/EmailService.java
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewRepository.java
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewReservation.java
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewSlot.java
  server/src/main/java/com/ryc/api/v2/interview/domain/NumberOfPeopleByInterviewDate.java
  server/src/main/java/com/ryc/api/v2/interview/domain/NumberOfPeopleByInterviewDateValidator.java
  server/src/main/java/com/ryc/api/v2/interview/infra/InterviewRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/interview/infra/entity/InterviewSlotEntity.java
  server/src/main/java/com/ryc/api/v2/interview/infra/jpa/InterviewReservationJpaRepository.java
  server/src/main/java/com/ryc/api/v2/interview/infra/jpa/InterviewSlotJpaRepository.java
  server/src/main/java/com/ryc/api/v2/interview/infra/mapper/InterviewSlotMapper.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/InterviewHttpApi.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/InterviewReminderUpdatedRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/InterviewSlotCreateRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/InterviewSlotDetailRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/MaxNumberOfPeopleUpdatedRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/response/InterviewReminderTimeResponse.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/response/InterviewSlotCreateResponse.java
  server/src/main/java/com/ryc/api/v2/interview/service/InterviewReminderService.java
  server/src/main/java/com/ryc/api/v2/interview/service/InterviewService.java
  server/src/main/resources/templates/interview-link.html
  server/src/main/resources/templates/interview-reminder.html
Labels: ⭐️ feature, 💻 BE

#580 Revert "[BE] 면접 도메인 API 수정"
  server/build.gradle
  server/src/main/java/com/ryc/api/config/WebConfig.java
  server/src/main/java/com/ryc/api/v2/common/dispatch/EmailSenderService.java
  server/src/main/java/com/ryc/api/v2/common/exception/code/InterviewErrorCode.java
  server/src/main/java/com/ryc/api/v2/email/domain/EmailValidator.java
  server/src/main/java/com/ryc/api/v2/email/domain/event/InterviewReminderEvent.java
  server/src/main/java/com/ryc/api/v2/email/domain/event/InterviewSlotEmailEvent.java
  server/src/main/java/com/ryc/api/v2/email/presentation/EmailHttpApi.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/request/EmailSendRequest.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/request/InterviewSlotEmailSendRequest.java
  server/src/main/java/com/ryc/api/v2/email/service/EmailService.java
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewRepository.java
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewReservation.java
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewSlot.java
  server/src/main/java/com/ryc/api/v2/interview/domain/NumberOfPeopleByInterviewDate.java
  server/src/main/java/com/ryc/api/v2/interview/domain/NumberOfPeopleByInterviewDateValidator.java
  server/src/main/java/com/ryc/api/v2/interview/infra/InterviewRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/interview/infra/entity/InterviewSlotEntity.java
  server/src/main/java/com/ryc/api/v2/interview/infra/jpa/InterviewReservationJpaRepository.java
  server/src/main/java/com/ryc/api/v2/interview/infra/jpa/InterviewSlotJpaRepository.java
  server/src/main/java/com/ryc/api/v2/interview/infra/mapper/InterviewSlotMapper.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/InterviewHttpApi.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/InterviewReminderUpdatedRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/InterviewSlotCreateRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/MaxNumberOfPeopleUpdatedRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/NumberOfPeopleByInterviewDateRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/response/InterviewReminderTimeResponse.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/response/InterviewSlotCreateResponse.java
  server/src/main/java/com/ryc/api/v2/interview/service/InterviewReminderService.java
  server/src/main/java/com/ryc/api/v2/interview/service/InterviewService.java
  server/src/main/resources/templates/interview-link.html
  server/src/main/resources/templates/interview-reminder.html
  server/src/test/resources/schema.sql
Labels: 🐛 bug, 💻 BE

#581 Revert "Revert "[BE] 면접 도메인 API 수정""
  server/src/main/java/com/ryc/api/v2/common/dispatch/EmailSenderService.java
  server/src/main/java/com/ryc/api/v2/common/exception/code/InterviewErrorCode.java
  server/src/main/java/com/ryc/api/v2/email/domain/EmailValidator.java
  server/src/main/java/com/ryc/api/v2/email/domain/event/InterviewReminderEvent.java
  server/src/main/java/com/ryc/api/v2/email/domain/event/InterviewSlotEmailEvent.java
  server/src/main/java/com/ryc/api/v2/email/presentation/EmailHttpApi.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/request/EmailSendRequest.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/request/InterviewSlotEmailSendRequest.java
  server/src/main/java/com/ryc/api/v2/email/service/EmailService.java
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewRepository.java
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewReservation.java
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewSlot.java
  server/src/main/java/com/ryc/api/v2/interview/domain/NumberOfPeopleByInterviewDate.java
  server/src/main/java/com/ryc/api/v2/interview/domain/NumberOfPeopleByInterviewDateValidator.java
  server/src/main/java/com/ryc/api/v2/interview/infra/InterviewRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/interview/infra/entity/InterviewSlotEntity.java
  server/src/main/java/com/ryc/api/v2/interview/infra/jpa/InterviewReservationJpaRepository.java
  server/src/main/java/com/ryc/api/v2/interview/infra/jpa/InterviewSlotJpaRepository.java
  server/src/main/java/com/ryc/api/v2/interview/infra/mapper/InterviewSlotMapper.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/InterviewHttpApi.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/InterviewReminderUpdatedRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/InterviewSlotCreateRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/InterviewSlotDetailRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/MaxNumberOfPeopleUpdatedRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/response/InterviewReminderTimeResponse.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/response/InterviewSlotCreateResponse.java
  server/src/main/java/com/ryc/api/v2/interview/service/InterviewReminderService.java
  server/src/main/java/com/ryc/api/v2/interview/service/InterviewService.java
  server/src/main/resources/templates/interview-link.html
  server/src/main/resources/templates/interview-reminder.html
Labels: 🐛 bug, 💻 BE

#583 [BE] entity와 JPQL 간의 필드 이름 불일치 해결
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewRepository.java
  server/src/main/java/com/ryc/api/v2/interview/infra/InterviewRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/interview/infra/jpa/InterviewSlotJpaRepository.java
  server/src/main/java/com/ryc/api/v2/interview/service/InterviewReminderService.java
Labels: 🐛 bug, 💻 BE

#587 [BE] 면접 리마인더 조회 시 NPE 해결
  server/src/main/java/com/ryc/api/v2/email/domain/EmailRepository.java
  server/src/main/java/com/ryc/api/v2/email/domain/EmailVerificationRepository.java
  server/src/main/java/com/ryc/api/v2/email/infra/EmailRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/email/infra/EmailVerificationRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/email/infra/jpa/EmailJpaRepository.java
  server/src/main/java/com/ryc/api/v2/email/infra/jpa/EmailVerificationJpaRepository.java
  server/src/main/java/com/ryc/api/v2/email/infra/scheduler/EmailCleanupScheduler.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/response/InterviewReminderTimeResponse.java
Labels: 🐛 bug, 💻 BE
