Repository Recruiting-Your-Club/ryc, pull requests merged in 2025-07, with the labels that each got.

#200 [FE] 메인페이지, 상세페이지 API 연결
  client/.gitignore
  client/package.json
  client/public/mockServiceWorker.js
  client/setupTests.js
  client/src/api/common/httpClient.ts
  client/src/api/common/httpError.ts
  client/src/api/common/httpRequest.ts
  client/src/api/common/types.ts
  client/src/api/domain/club/club.ts
  client/src/api/domain/club/types.ts
  client/src/api/domain/index.ts
  client/src/api/index.ts
  client/src/api/queryFactory/clubQueries.ts
  client/src/api/queryFactory/index.ts
  client/src/api/querykeyFactory.ts
  client/src/components/ClubBox/ClubBox.tsx
  client/src/components/ClubBox/types.ts
  client/src/components/MainCard/MainCard.style.tsx
  client/src/components/MainCard/MainCard.tsx
  client/src/components/MainCard/TagStatus.tsx
  client/src/components/MainCard/types.ts
  client/src/components/_common/Tag/Tag.style.ts
  client/src/constants/api.ts
  client/src/constants/club.ts
  client/src/index.tsx
  client/src/layouts/UserLayout/UserLayout.tsx
  client/src/mocks/data/club/clubAllList.json
  client/src/mocks/data/club/clubDetail.json
  client/src/mocks/handlers/clubHandler.ts
  client/src/mocks/handlers/index.ts
  client/src/mocks/server/browser.ts
  client/src/mocks/server/node.ts
  client/src/pages/ClubDetailPage/ClubDetailPage.tsx
  client/src/pages/ClubDetailPage/ClubIntroPage/ClubIntroPage.style.ts
  client/src/pages/ClubDetailPage/ClubIntroPage/ClubIntroPage.tsx
  client/src/pages/LoadingPage/DetailLoadingPage/DetailLoadingPage.style.tsx
  client/src/pages/LoadingPage/DetailLoadingPage/DetailLoadingPage.tsx
  client/src/pages/LoadingPage/DetailLoadingPage/index.tsx
  client/src/pages/LoadingPage/MainLoadingPage/MainLoadingPage.style.ts
  client/src/pages/LoadingPage/MainLoadingPage/MainLoadingPage.tsx
  client/src/pages/LoadingPage/MainLoadingPage/index.tsx
  client/src/pages/LoadingPage/index.tsx
  client/src/pages/MainPage/MainPage.style.ts
  client/src/pages/MainPage/MainPage.tsx
  client/src/pages/MainPage/types.ts
  client/src/pages/TestPage/index.tsx
  client/src/pages/index.tsx
  client/src/router.tsx
  client/src/utils/changeCategory.ts
  client/tsconfig.json
  client/webpack.common.js
  client/yarn.lock
Labels: ⭐️ feature, 🚀FE

#210 [FE] 동아리 생성 페이지 구현
  client/package.json
  client/src/assets/images/upload.svg
  client/src/components/ImageEditDialog/ImageEdit.style.ts
  client/src/components/ImageEditDialog/ImageEditDialog.tsx
  client/src/components/ImageEditDialog/index.ts
  client/src/components/ImageEditDialog/types.ts
  client/src/components/ImageEditDialog/utils.ts
  client/src/components/_common/ImageRegister/ImageRegister.style.ts
  client/src/components/_common/ImageRegister/ImageRegister.tsx
  client/src/components/_common/ImageRegister/index.ts
  client/src/components/_common/ImageRegister/types.ts
  client/src/components/_common/index.tsx
  client/src/components/index.tsx
  client/src/pages/ClubCreatePage/ClubCreatePage.style.ts
  client/src/pages/ClubCreatePage/ClubCreatePage.tsx
  client/src/pages/ClubCreatePage/index.tsx
  client/src/pages/TestPage/index.tsx
  client/src/pages/index.tsx
  client/src/router.tsx
  client/yarn.lock
Labels: ⭐️ feature, 🚀FE

#217 [FE] 나의 동아리 찾기 페이지 구현
  client/src/pages/MyClubPage/MyClubPage.style.tsx
  client/src/pages/MyClubPage/MyClubPage.tsx
  client/src/pages/MyClubPage/index.tsx
  client/src/pages/TestPage/index.tsx
  client/src/pages/index.tsx
  client/src/router.tsx
Labels: 🚀FE

#219 [FE] 동아리 면접 예약 페이지 구현
  client/src/pages/ReservationPage/Reservation.style.ts
  client/src/pages/ReservationPage/ReservationPage.tsx
  client/src/pages/ReservationPage/index.ts
  client/src/pages/index.tsx
  client/src/router.tsx
Labels: 🚀FE

#258 [BE] CORS 설정 및 image URL에 대한 DB 자료형 변경
  server/src/main/java/com/ryc/api/config/WebConfig.java
  server/src/main/java/com/ryc/api/v2/admin/infra/entity/AdminEntity.java
  server/src/main/java/com/ryc/api/v2/club/infra/entity/ClubEntity.java
  server/src/main/java/com/ryc/api/v2/common/aop/aspect/ClubAspect.java
Labels: 🔨 refactor, 💻 BE

#271 Fix: allowOrigins
  server/src/main/java/com/ryc/api/config/WebConfig.java
  server/src/main/java/com/ryc/api/v2/email/application/EmailService.java
Labels: 🐛 bug, 💻 BE

#272 [FE] AccessToken 및 RefreshToken 인증 플로우 구현
  client/package.json
  client/src/api/common/httpClient.ts
  client/src/api/common/httpRequest.ts
  client/src/api/domain/auth/auth.ts
  client/src/api/domain/auth/types.ts
  client/src/api/domain/index.ts
  client/src/api/domain/myClub/myClub.ts
  client/src/api/domain/myClub/types.ts
  client/src/api/queryFactory/myClubQueries.ts
  client/src/api/querykeyFactory.ts
  client/src/components/QuestionForm/QuestionForm.tsx
  client/src/constants/staleTime.ts
  client/src/hooks/useLogin.tsx
  client/src/hooks/useRegister.tsx
  client/src/pages/AuthPage/LoginPage/LoginPage.tsx
  client/src/pages/AuthPage/RegisterPage/RegisterPage.tsx
  client/src/pages/ClubApplyPage/PersonalInfoPage/ClubApplyPersonalInfoPage.tsx
  client/src/pages/MyClubPage/MyClubPage.tsx
  client/src/pages/RecruitCreatePage/RecruitCreatePage.tsx
  client/src/stores/authStore.ts
  client/src/stores/index.ts
  client/tsconfig.json
  client/yarn.lock
Labels: ⭐️ feature, 🚀FE

#240 [REFACTOR/FE] 동아리 지원 페이지 리팩토링
  client/src/assets/images/info.svg
  client/src/components/ClubNavigation/ClubNavigation.tsx
  client/src/components/ClubNavigation/types.ts
  client/src/components/ClubSubmitCard/ClubSubmitCard.style.ts
  client/src/components/ClubSubmitCard/ClubSubmitCard.tsx
  client/src/components/ClubSubmitCard/types.ts
  client/src/components/QuestionDropdown/QuestionDropdown.style.ts
  client/src/components/QuestionDropdown/QuestionDropdown.tsx
  client/src/components/QuestionDropdown/index.tsx
  client/src/components/QuestionDropdown/types.ts
  client/src/components/RecruitCard/RecruitCard.tsx
  client/src/components/RecruitDialog/RecruitDialog.tsx
  client/src/components/_common/Tooltip/Tooltip.style.ts
  client/src/components/_common/Tooltip/Tooltip.tsx
  client/src/components/_common/Tooltip/types.ts
  client/src/components/_common/index.tsx
  client/src/components/index.tsx
  client/src/hooks/index.tsx
  client/src/hooks/useMediaQuery.tsx
  client/src/pages/ClubApplyPage/ClubApplyPage.style.ts
  client/src/pages/ClubApplyPage/ClubApplyPage.tsx
  client/src/pages/ClubApplyPage/DetailQuestionPage/ClubApplyDetailQuestionPage.style.ts
  client/src/pages/ClubApplyPage/DetailQuestionPage/ClubApplyDetailQuestionPage.tsx
  client/src/pages/ClubApplyPage/PersonalInfoPage/ClubApplyPersonalInfoPage.style.ts
  client/src/pages/ClubApplyPage/PersonalInfoPage/ClubApplyPersonalInfoPage.tsx
  client/src/pages/ClubApplyPage/types.ts
  client/src/pages/RecruitmentPage/RecruitmentPage.tsx
  client/src/pages/index.tsx
  client/src/utils/compareTime.ts
Labels: 🔨 refactor, 🚀FE

#277 [BE] 회원가입 시 이메일 중복 확인 API
  server/src/main/java/com/ryc/api/v2/admin/presentation/AdminController.java
  server/src/main/java/com/ryc/api/v2/admin/presentation/AdminHttpApi.java
  server/src/main/java/com/ryc/api/v2/admin/presentation/response/AdminEmailDuplicatedResponse.java
  server/src/main/java/com/ryc/api/v2/admin/service/AdminService.java
  server/src/main/java/com/ryc/api/v2/common/exception/GlobalExceptionHandler.java
Labels: ⭐️ feature, 💻 BE

#275 [BE] 동아리 역할에 대한 인가를 수행하는 AOP
  server/src/main/java/com/ryc/api/config/SecurityConfiguration.java
  server/src/main/java/com/ryc/api/config/SwaggerConfiguration.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/AnnouncementHttpApi.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/AnnouncementHttpApiImpl.java
  server/src/main/java/com/ryc/api/v2/announcement/service/AnnouncementService.java
  server/src/main/java/com/ryc/api/v2/club/presentation/ClubHttpApi.java
  server/src/main/java/com/ryc/api/v2/club/service/ClubFacade.java
  server/src/main/java/com/ryc/api/v2/club/service/ClubService.java
  server/src/main/java/com/ryc/api/v2/common/aop/aspect/ClubRoleAspect.java
  server/src/main/java/com/ryc/api/v2/common/aop/dto/ClubRoleSecuredDto.java
  server/src/main/java/com/ryc/api/v2/common/exception/GlobalExceptionHandler.java
  server/src/main/java/com/ryc/api/v2/common/exception/code/ClubErrorCode.java
  server/src/main/java/com/ryc/api/v2/email/application/EmailService.java
  server/src/main/java/com/ryc/api/v2/email/presentation/EmailHttpApi.java
  server/src/main/java/com/ryc/api/v2/role/presentation/ClubRoleHttpApi.java
  server/src/main/java/com/ryc/api/v2/role/service/ClubRoleService.java
Labels: 📑 docs, ⭐️ feature, 💻 BE

#266 [BE] 지원 도메인 영속성 계층 구현
  server/src/main/java/com/ryc/api/v2/applicant/domain/Applicant.java
  server/src/main/java/com/ryc/api/v2/applicant/domain/ApplicantRepository.java
  server/src/main/java/com/ryc/api/v2/applicant/domain/enums/ApplicantStatus.java
  server/src/main/java/com/ryc/api/v2/applicant/infra/ApplicantRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/applicant/infra/entity/ApplicantEntity.java
  server/src/main/java/com/ryc/api/v2/applicant/infra/jpa/ApplicantJpaRepository.java
  server/src/main/java/com/ryc/api/v2/applicant/infra/mapper/ApplicantMapper.java
  server/src/main/java/com/ryc/api/v2/application/domain/Answer.java
  server/src/main/java/com/ryc/api/v2/application/domain/AnswerChoice.java
  server/src/main/java/com/ryc/api/v2/application/domain/Application.java
  server/src/main/java/com/ryc/api/v2/application/domain/ApplicationRepository.java
  server/src/main/java/com/ryc/api/v2/application/infra/ApplicationRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/application/infra/entity/AnswerChoiceEntity.java
  server/src/main/java/com/ryc/api/v2/application/infra/entity/AnswerEntity.java
  server/src/main/java/com/ryc/api/v2/application/infra/entity/ApplicationEntity.java
  server/src/main/java/com/ryc/api/v2/application/infra/jpa/AnswerChoiceJpaRepository.java
  server/src/main/java/com/ryc/api/v2/application/infra/jpa/AnswerJpaRepository.java
  server/src/main/java/com/ryc/api/v2/application/infra/jpa/ApplicationJpaRepository.java
  server/src/main/java/com/ryc/api/v2/application/infra/mapper/AnswerChoiceMapper.java
  server/src/main/java/com/ryc/api/v2/application/infra/mapper/AnswerMapper.java
  server/src/main/java/com/ryc/api/v2/application/infra/mapper/ApplicationMapper.java
Labels: 💻 BE

#238 [REFACTOR/FE] Rating 컴포넌트 리펙토링
  client/.gitignore
  client/src/assets/images/star.svg
  client/src/components/_common/Rating/Rating.stories.tsx
  client/src/components/_common/Rating/Rating.style.ts
  client/src/components/_common/Rating/Rating.tsx
  client/src/components/_common/Rating/Star.tsx
  client/src/components/_common/Rating/types.ts
  client/src/constants/rating.ts
Labels: 🔨 refactor, 🚀FE

#268 [FE/REFACTOR] 사이드바 리팩토링
  client/src/api/domain/announcement/announcement.ts
  client/src/api/domain/announcement/types.ts
  client/src/api/domain/club/club.ts
  client/src/api/domain/club/types.ts
  client/src/api/domain/index.ts
  client/src/api/queryFactory/announcementQueries.ts
  client/src/api/queryFactory/clubQueries.ts
  client/src/api/querykeyFactory.ts
  client/src/assets/images/chevron-double-right.svg
  client/src/assets/images/chevron-up-down.svg
  client/src/assets/images/ssoc.png
  client/src/components/SideBar/SideBar.style.tsx
  client/src/components/SideBar/SideBar.tsx
  client/src/components/_common/index.tsx
  client/src/layouts/ManagerLayout/ManagerLayout.style.ts
  client/src/layouts/ManagerLayout/ManagerLayout.tsx
  client/src/mocks/data/announcement/announcementByClub.json
  client/src/mocks/data/club/myClubList.json
  client/src/mocks/handlers/announcementHandler.ts
  client/src/mocks/handlers/clubHandler.ts
  client/src/mocks/handlers/index.ts
  client/src/router.tsx
  client/src/styles/global.ts
Labels: 🔨 refactor, 🚀FE
