Repository Recruiting-Your-Club/ryc, pull requests merged in 2025-06, with the labels that each got.

#176 [FE] Editor 컴포넌트 구현
  client/src/assets/images/chevron-down.svg
  client/src/assets/images/chevron-up.svg
  client/src/assets/images/list_decimal.svg
  client/src/assets/images/list_disc.svg
  client/src/assets/images/option_code.svg
  client/src/assets/images/option_divider.svg
  client/src/assets/images/option_image.svg
  client/src/assets/images/option_link.svg
  client/src/assets/images/option_quote.svg
  client/src/assets/images/text-align-center.svg
  client/src/assets/images/text-align-justify.svg
  client/src/assets/images/text-align-left.svg
  client/src/assets/images/text-align-right.svg
  client/src/assets/images/text-background-color.svg
  client/src/assets/images/text-bold.svg
  client/src/assets/images/text-color.svg
  client/src/assets/images/text-italic.svg
  client/src/assets/images/text-strikethrough.svg
  client/src/assets/images/text-underline.svg
  client/src/components/_common/Checkbox/BaseCheckbox.tsx
  client/src/components/_common/Checkbox/Checkbox.stories.tsx
  client/src/components/_common/Checkbox/Checkbox.style.ts
  client/src/components/_common/Checkbox/CheckboxContext.ts
  client/src/components/_common/Checkbox/CheckboxControl.tsx
  client/src/components/_common/Checkbox/CheckboxHiddenInput.tsx
  client/src/components/_common/Checkbox/CheckboxLabel.tsx
  client/src/components/_common/Checkbox/CheckboxRoot.tsx
  client/src/components/_common/Checkbox/index.tsx
  client/src/components/_common/Editor/BaseEditor.tsx
  client/src/components/_common/Editor/Editor.style.ts
  client/src/components/_common/Editor/EditorContext.ts
  client/src/components/_common/Editor/EditorRoot.tsx
  client/src/components/_common/Editor/EditorTextColorPicker.tsx
  client/src/components/_common/Editor/EditorTextarea.tsx
  client/src/components/_common/Editor/EditorToolbar.tsx
  client/src/components/_common/Editor/index.tsx
  client/src/components/_common/Editor/types.ts
  client/src/components/_common/Editor/utils/alignment.ts
  client/src/components/_common/Editor/utils/list.ts
  client/src/components/_common/Editor/utils/options.ts
  client/src/components/_common/Editor/utils/range.ts
  client/src/components/_common/Editor/utils/selection.ts
  client/src/components/_common/Editor/utils/textStyles.ts
  client/src/components/_common/index.tsx
  client/src/components/index.tsx
  client/src/constants/Editor.ts
  client/src/pages/TestPage/index.tsx
  client/src/utils/hexToRgb.ts
Labels: ⭐️ feature, 🚀FE

#214 [REFACTOR/FE] Select 컴포넌트 리펙토링
  client/src/components/Select/Select.stories.tsx
  client/src/components/Select/Select.styles.ts
  client/src/components/Select/Select.tsx
  client/src/components/Select/SelectContent.tsx
  client/src/components/Select/SelectContext.ts
  client/src/components/Select/SelectGroup.tsx
  client/src/components/Select/SelectItem.tsx
  client/src/components/Select/SelectLabel.tsx
  client/src/components/Select/SelectTrigger.tsx
  client/src/components/Select/SelectValue.tsx
  client/src/components/Select/types.ts
  client/src/pages/TestPage/index.tsx
Labels: 🔨 refactor, 🚀FE

#183 [FE] Dropdown 컴포넌트 구현
  client/src/assets/images/right_arrow.svg
  client/src/components/_common/Dropdown/Dropdown.stories.tsx
  client/src/components/_common/Dropdown/Dropdown.styles.ts
  client/src/components/_common/Dropdown/Dropdown.tsx
  client/src/components/_common/Dropdown/DropdownContent.tsx
  client/src/components/_common/Dropdown/DropdownContext.ts
  client/src/components/_common/Dropdown/DropdownGroup.tsx
  client/src/components/_common/Dropdown/DropdownItem.tsx
  client/src/components/_common/Dropdown/DropdownLabel.tsx
  client/src/components/_common/Dropdown/DropdownSeperator.tsx
  client/src/components/_common/Dropdown/DropdownSub.tsx
  client/src/components/_common/Dropdown/DropdownSubContent.tsx
  client/src/components/_common/Dropdown/DropdownSubTrigger.tsx
  client/src/components/_common/Dropdown/DropdownTrigger.tsx
  client/src/components/_common/Dropdown/index.tsx
  client/src/components/_common/Dropdown/types.ts
  client/src/components/_common/Slot/Slot.tsx
  client/src/components/_common/Slot/index.tsx
  client/src/hooks/components/useClickOutside.tsx
  client/src/pages/TestPage/index.tsx
Labels: ⭐️ feature, 🚀FE

#216 [BE] 동아리 생성 API 수정
  server/src/main/java/com/ryc/api/config/SecurityConfiguration.java
  server/src/main/java/com/ryc/api/v2/admin/domain/AdminRepository.java
  server/src/main/java/com/ryc/api/v2/admin/infra/AdminRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/announcement/service/AnnouncementService.java
  server/src/main/java/com/ryc/api/v2/auth/domain/.gitkeep
  server/src/main/java/com/ryc/api/v2/auth/domain/Admin.java
  server/src/main/java/com/ryc/api/v2/auth/domain/AdminDefaultRole.java
  server/src/main/java/com/ryc/api/v2/auth/domain/AdminRepository.java
  server/src/main/java/com/ryc/api/v2/auth/infra/.gitkeep
  server/src/main/java/com/ryc/api/v2/auth/infra/AdminRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/auth/infra/entity/AdminEntity.java
  server/src/main/java/com/ryc/api/v2/auth/infra/jpa/AdminJpaRepository.java
  server/src/main/java/com/ryc/api/v2/auth/infra/mapper/AdminMapper.java
  server/src/main/java/com/ryc/api/v2/auth/presentation/request/RegisterRequest.java
  server/src/main/java/com/ryc/api/v2/auth/service/AuthService.java
  server/src/main/java/com/ryc/api/v2/club/business/ClubAnnouncementFacade.java
  server/src/main/java/com/ryc/api/v2/club/business/ClubService.java
  server/src/main/java/com/ryc/api/v2/club/domain/Club.java
  server/src/main/java/com/ryc/api/v2/club/domain/ClubRepository.java
  server/src/main/java/com/ryc/api/v2/club/domain/Role.java
  server/src/main/java/com/ryc/api/v2/club/infra/ClubRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/club/infra/entity/ClubEntity.java
  server/src/main/java/com/ryc/api/v2/club/infra/entity/RoleEntity.java
  server/src/main/java/com/ryc/api/v2/club/infra/jpa/ClubJpaRepository.java
  server/src/main/java/com/ryc/api/v2/club/infra/jpa/RoleJpaRepository.java
  server/src/main/java/com/ryc/api/v2/club/infra/mapper/RoleMapper.java
  server/src/main/java/com/ryc/api/v2/club/presentation/ClubHttpApi.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubCreateRequest.java
  server/src/main/java/com/ryc/api/v2/security/dto/CustomUserDetail.java
  server/src/main/java/com/ryc/api/v2/security/exception/RestAuthenticationEntryPoint.java
  server/src/main/java/com/ryc/api/v2/security/exception/TokenAccessDeniedHandler.java
  server/src/main/java/com/ryc/api/v2/security/filter/EmailPasswordAuthenticationFilter.java
  server/src/main/java/com/ryc/api/v2/security/filter/JwtAuthenticationFilter.java
  server/src/main/java/com/ryc/api/v2/security/service/CustomUserDetailService.java
  server/src/test/java/com/ryc/api/v2/club/business/ClubServiceTest.java
  server/src/test/java/com/ryc/api/v2/club/infra/ClubRepositoryImplTest.java
  server/src/test/java/com/ryc/api/v2/club/presentation/ClubHttpApiTest.java
Labels: ⭐️ feature, 💻 BE
