Repository Recruiting-Your-Club/ryc, pull requests merged in 2025-08, with the labels that each got.

#307 [BE/HOTFIX] 서버 인증 whitelist 수정 및 배포시 로그 파일 생성 job 수정
  .github/workflows/server-dev-deploy.yml
  server/src/main/java/com/ryc/api/config/SecurityConfiguration.java
  server/src/main/java/com/ryc/api/config/SwaggerConfiguration.java
  server/src/main/java/com/ryc/api/v2/announcement/domain/Announcement.java
  server/src/main/java/com/ryc/api/v2/announcement/infra/entity/AnnouncementEntity.java
  server/src/main/java/com/ryc/api/v2/announcement/infra/mapper/AnnouncementMapper.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementCreateRequest.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/response/AnnouncementGetAllResponse.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/response/AnnouncementGetDetailResponse.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/response/AnnouncementUpdateResponse.java
  server/src/main/java/com/ryc/api/v2/club/service/ClubService.java
Labels: 🐛 bug, 💻 BE

#310 [BE] Path 패턴 매칭 수정
  server/src/main/java/com/ryc/api/config/SecurityConfiguration.java
  server/src/main/java/com/ryc/api/config/SwaggerConfiguration.java
Labels: 🐛 bug, 💻 BE

#316 [BE] 동아리 수정 API 리팩토링
  server/src/main/java/com/ryc/api/v2/announcement/presentation/AnnouncementHttpApi.java
  server/src/main/java/com/ryc/api/v2/applicant/presentation/dto/request/ApplicantPersonalInfoCreateRequest.java
  server/src/main/java/com/ryc/api/v2/club/domain/Club.java
  server/src/main/java/com/ryc/api/v2/club/domain/ClubDetailImage.java
  server/src/main/java/com/ryc/api/v2/club/domain/ClubSummary.java
  server/src/main/java/com/ryc/api/v2/club/domain/ClubTag.java
  server/src/main/java/com/ryc/api/v2/club/domain/enums/Category.java
  server/src/main/java/com/ryc/api/v2/club/domain/vo/ClubDetailImage.java
  server/src/main/java/com/ryc/api/v2/club/domain/vo/ClubSummary.java
  server/src/main/java/com/ryc/api/v2/club/domain/vo/ClubTag.java
  server/src/main/java/com/ryc/api/v2/club/infra/ClubRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/club/infra/entity/ClubDetailImageEntity.java
  server/src/main/java/com/ryc/api/v2/club/infra/entity/ClubEntity.java
  server/src/main/java/com/ryc/api/v2/club/infra/entity/ClubSummaryEntity.java
  server/src/main/java/com/ryc/api/v2/club/infra/entity/ClubTagEntity.java
  server/src/main/java/com/ryc/api/v2/club/infra/mapper/ClubDetailImageMapper.java
  server/src/main/java/com/ryc/api/v2/club/infra/mapper/ClubMapper.java
  server/src/main/java/com/ryc/api/v2/club/infra/mapper/ClubSummaryMapper.java
  server/src/main/java/com/ryc/api/v2/club/infra/mapper/ClubTagMapper.java
  server/src/main/java/com/ryc/api/v2/club/presentation/ClubHttpApi.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubDetailImageRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubSummaryRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubTagRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/response/AllClubGetResponse.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/response/ClubGetByAdminIdResponse.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/response/DetailClubResponse.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/response/SimpleClubResponse.java
  server/src/main/java/com/ryc/api/v2/club/service/ClubAnnouncementFacade.java
  server/src/main/java/com/ryc/api/v2/club/service/ClubFacade.java
  server/src/main/java/com/ryc/api/v2/club/service/ClubService.java
  server/src/main/java/com/ryc/api/v2/common/aop/aspect/ClubAspect.java
  server/src/main/java/com/ryc/api/v2/common/exception/code/ClubErrorCode.java
  server/src/main/java/com/ryc/api/v2/interview/infra/entity/InterviewSlotEntity.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/InterviewHttpApi.java
  server/src/main/java/com/ryc/api/v2/role/presentation/ClubRoleHttpApi.java
  server/src/main/java/com/ryc/api/v2/role/service/ClubRoleService.java
Labels: ⭐️ feature, 💻 BE

#325 [ALL] develop 변경사항 default 브랜치 반영
  .github/workflows/front-deploy.yml
  .github/workflows/server-dev-deploy.yml
  server/src/main/java/com/ryc/api/v2/announcement/domain/Announcement.java
  server/src/main/java/com/ryc/api/v2/announcement/domain/vo/AnnouncementPeriodInfo.java
  server/src/main/java/com/ryc/api/v2/announcement/infra/AnnouncementRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/AnnouncementHttpApi.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementCreateRequest.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementPeriodInfoRequest.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/response/AnnouncementGetDetailResponse.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/response/AnnouncementUpdateResponse.java
  server/src/main/java/com/ryc/api/v2/applicant/presentation/dto/request/ApplicantPersonalInfoCreateRequest.java
  server/src/main/java/com/ryc/api/v2/auth/presentation/AuthController.java
  server/src/main/java/com/ryc/api/v2/club/domain/Club.java
  server/src/main/java/com/ryc/api/v2/club/domain/ClubDetailImage.java
  server/src/main/java/com/ryc/api/v2/club/domain/ClubSummary.java
  server/src/main/java/com/ryc/api/v2/club/domain/ClubTag.java
  server/src/main/java/com/ryc/api/v2/club/domain/enums/Category.java
  server/src/main/java/com/ryc/api/v2/club/domain/vo/ClubDetailImage.java
  server/src/main/java/com/ryc/api/v2/club/domain/vo/ClubSummary.java
  server/src/main/java/com/ryc/api/v2/club/domain/vo/ClubTag.java
  server/src/main/java/com/ryc/api/v2/club/infra/ClubRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/club/infra/entity/ClubDetailImageEntity.java
  server/src/main/java/com/ryc/api/v2/club/infra/entity/ClubEntity.java
  server/src/main/java/com/ryc/api/v2/club/infra/entity/ClubSummaryEntity.java
  server/src/main/java/com/ryc/api/v2/club/infra/entity/ClubTagEntity.java
  server/src/main/java/com/ryc/api/v2/club/infra/mapper/ClubDetailImageMapper.java
  server/src/main/java/com/ryc/api/v2/club/infra/mapper/ClubMapper.java
  server/src/main/java/com/ryc/api/v2/club/infra/mapper/ClubSummaryMapper.java
  server/src/main/java/com/ryc/api/v2/club/infra/mapper/ClubTagMapper.java
  server/src/main/java/com/ryc/api/v2/club/presentation/ClubHttpApi.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubDetailImageRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubSummaryRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubTagRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/response/AllClubGetResponse.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/response/ClubGetByAdminIdResponse.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/response/DetailClubResponse.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/response/SimpleClubResponse.java
  server/src/main/java/com/ryc/api/v2/club/service/ClubAnnouncementFacade.java
  server/src/main/java/com/ryc/api/v2/club/service/ClubFacade.java
  server/src/main/java/com/ryc/api/v2/club/service/ClubService.java
  server/src/main/java/com/ryc/api/v2/common/aop/aspect/ClubAspect.java
  server/src/main/java/com/ryc/api/v2/common/exception/code/ClubErrorCode.java
  server/src/main/java/com/ryc/api/v2/interview/infra/entity/InterviewSlotEntity.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/InterviewHttpApi.java
  server/src/main/java/com/ryc/api/v2/role/presentation/ClubRoleHttpApi.java
  server/src/main/java/com/ryc/api/v2/role/service/ClubRoleService.java
  server/src/main/java/com/ryc/api/v2/security/filter/EmailPasswordAuthenticationFilter.java
Labels: 🌍ALL

#329 [BE/HOTFIX] 개발환경 Refresh Token 테스트를 위한, CORS 재설정 및 RT쿠키 설정 완화
  server/src/main/java/com/ryc/api/v2/auth/presentation/AuthController.java
  server/src/main/java/com/ryc/api/v2/security/filter/EmailPasswordAuthenticationFilter.java
Labels: 🐛 bug, 💻 BE

#273 [FE/REFACTOR] 서류 평가 페이지 리팩토링
  client/src/api/domain/applicant/applicant.ts
  client/src/api/domain/applicant/types.ts
  client/src/api/domain/evaluation/evaluation.ts
  client/src/api/domain/evaluation/types.ts
  client/src/api/domain/index.ts
  client/src/api/domain/step/step.ts
  client/src/api/domain/step/types.ts
  client/src/api/queryFactory/applicantQueries.ts
  client/src/api/queryFactory/evaluationQueries.ts
  client/src/api/queryFactory/index.ts
  client/src/api/queryFactory/stepQueries.ts
  client/src/api/querykeyFactory.ts
  client/src/components/ApplicantList/ApplicantList.tsx
  client/src/components/ApplicantList/types.ts
  client/src/components/ApplicantMiniCard/types.ts
  client/src/components/EvaluationBox/EvaluationBox.style.ts
  client/src/components/EvaluationBox/EvaluationBox.tsx
  client/src/components/EvaluationBox/types.ts
  client/src/components/InformationBox/InformationBox.style.ts
  client/src/components/InformationBox/InformationBox.tsx
  client/src/components/InformationBox/types.ts
  client/src/components/InterviewSettingDialog/InterviewSettingDialog.style.ts
  client/src/components/InterviewSettingDialog/InterviewSettingDialog.tsx
  client/src/components/InterviewTimeBox/InterviewTimeBox.tsx
  client/src/components/PersonalScoreCard/PersonalScoreCard.style.ts
  client/src/components/PersonalScoreCard/PersonalScoreCard.tsx
  client/src/components/PersonalScoreCard/types.tsx
  client/src/components/PlainEmailDialog/PlainEmailDialog.tsx
  client/src/components/QuestionForm/QuestionForm.tsx
  client/src/components/_common/Avatar/Avatar.tsx
  client/src/components/_common/Editor/EditorToolbar.tsx
  client/src/hooks/mutations/evaluationMutations.ts
  client/src/index.tsx
  client/src/mocks/data/applicant/applicantDocumentList.json
  client/src/mocks/data/evaluation/applicationEvaluationDetail.json
  client/src/mocks/data/evaluation/myApplicationEvaluationStatus.json
  client/src/mocks/data/step/stepApplicantList.json
  client/src/mocks/handlers/applicantHandler.ts
  client/src/mocks/handlers/evaluationHandler.ts
  client/src/mocks/handlers/index.ts
  client/src/mocks/handlers/stepHandler.ts
  client/src/pages/DocumentEvaluationPage/DocumentEvaluationPage.tsx
Labels: 🔨 refactor, 🚀FE

#334 [BE] Not Found 예외 처리 수정
  server/src/main/java/com/ryc/api/v1/club/service/ClubServiceImpl.java
  server/src/main/java/com/ryc/api/v2/announcement/infra/AnnouncementRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/applicant/infra/ApplicantRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/application/infra/ApplicationRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/applicationForm/infra/ApplicationFormRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/auth/service/AuthService.java
  server/src/main/java/com/ryc/api/v2/club/infra/ClubRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/common/aop/aspect/ClubAspect.java
  server/src/main/java/com/ryc/api/v2/common/exception/GlobalExceptionHandler.java
  server/src/main/java/com/ryc/api/v2/evaluation/infra/EvaluationRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/file/infra/FileMetaDataRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/interview/domain/InterviewSlot.java
  server/src/main/java/com/ryc/api/v2/interview/infra/InterviewRepositoryImpl.java
Labels: 🐛 bug, 💻 BE

#297 [FE] Table 공통 컴포넌트 제작
  monorepo/apps/admin/src/api/querykeyFactory.ts
  monorepo/apps/admin/src/pages/TestPage/index.tsx
  monorepo/packages/ui/src/components/Table/Table.style.ts
  monorepo/packages/ui/src/components/Table/Table.tsx
  monorepo/packages/ui/src/components/Table/TableBody.tsx
  monorepo/packages/ui/src/components/Table/TableCell.tsx
  monorepo/packages/ui/src/components/Table/TableColumnHeaderCell.tsx
  monorepo/packages/ui/src/components/Table/TableHeader.tsx
  monorepo/packages/ui/src/components/Table/TableRow.tsx
  monorepo/packages/ui/src/components/Table/index.ts
  monorepo/packages/ui/src/components/Table/types.ts
  monorepo/packages/ui/src/components/index.ts
Labels: ⭐️ feature, 🚀FE

#378 [FE] 관리자페이지 사이드바 페이지 연결 및 공고 생성 페이지 미흡한 UI 구현
  monorepo/apps/admin/src/api/domain/announcement/types.ts
  monorepo/apps/admin/src/api/queryFactory/announcementQueries.ts
  monorepo/apps/admin/src/components/DatePicker/DatePicker.style.ts
  monorepo/apps/admin/src/components/DatePicker/DatePicker.tsx
  monorepo/apps/admin/src/components/DatePicker/index.ts
  monorepo/apps/admin/src/components/DatePicker/types.ts
  monorepo/apps/admin/src/components/DialogSection/DialogSection.style.ts
  monorepo/apps/admin/src/components/DialogSection/DialogSection.tsx
  monorepo/apps/admin/src/components/DialogSection/index.ts
  monorepo/apps/admin/src/components/DialogSection/types.ts
  monorepo/apps/admin/src/components/TagInput/TagInput.style.ts
  monorepo/apps/admin/src/components/TagInput/TagInput.tsx
  monorepo/apps/admin/src/components/TagInput/index.ts
  monorepo/apps/admin/src/components/TagInput/types.ts
  monorepo/apps/admin/src/components/index.ts
  monorepo/apps/admin/src/constants/descriptionStep.ts
  monorepo/apps/admin/src/pages/AnnouncementPage/AnnouncementPage.tsx
  monorepo/apps/admin/src/pages/AnnouncementPage/DetailQuestionPage/DetailQuestionPage.tsx
  monorepo/apps/admin/src/pages/AnnouncementPage/RecruitmenPage/RecruitmentPage.tsx
  monorepo/apps/admin/src/pages/AnnouncementPage/types.ts
  monorepo/apps/admin/src/pages/NonAnnouncementPage/NonAnnouncement.style.ts
  monorepo/apps/admin/src/pages/NonAnnouncementPage/NonAnnouncementPage.tsx
  monorepo/apps/admin/src/pages/NonAnnouncementPage/index.ts
  monorepo/apps/admin/src/pages/RecruitCreatePage/DescriptionStep/DescriptionStep.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/DescriptionStep/types.ts
  monorepo/apps/admin/src/pages/RecruitCreatePage/PreviewStep/PreviewStep.style.ts
  monorepo/apps/admin/src/pages/RecruitCreatePage/PreviewStep/PreviewStep.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/PreviewStep/index.ts
  monorepo/apps/admin/src/pages/RecruitCreatePage/PreviewStep/types.ts
  monorepo/apps/admin/src/pages/RecruitCreatePage/RecruitCreatePage.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/types.ts
  monorepo/apps/admin/src/pages/index.ts
  monorepo/apps/admin/src/router.tsx
  monorepo/packages/assets/images/file-normal.svg
  monorepo/packages/assets/images/x-free.svg
  monorepo/packages/hooks/src/useFileUpload.tsx
  monorepo/packages/ui/src/components/Dropdown/Dropdown.tsx
  monorepo/packages/ui/src/components/Editor/EditorToolbar.tsx
Labels: ⭐️ feature, 🚀FE

#376 [BE] 공고 상태 값 업데이트
  server/src/main/java/com/ryc/api/v2/announcement/domain/Announcement.java
  server/src/main/java/com/ryc/api/v2/announcement/domain/AnnouncementRepository.java
  server/src/main/java/com/ryc/api/v2/announcement/domain/enums/AnnouncementStatus.java
  server/src/main/java/com/ryc/api/v2/announcement/infra/AnnouncementRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/announcement/infra/entity/AnnouncementEntity.java
  server/src/main/java/com/ryc/api/v2/announcement/infra/jpa/AnnouncementJpaRepository.java
  server/src/main/java/com/ryc/api/v2/announcement/infra/mapper/AnnouncementMapper.java
  server/src/main/java/com/ryc/api/v2/announcement/infra/scheduler/AnnouncementStatusScheduler.java
  server/src/main/java/com/ryc/api/v2/announcement/service/AnnouncementService.java
Labels: 🔨 refactor, 💻 BE

#394 [FE/REFACTOR] UI 오류 개선 및 기타 수정
  monorepo/apps/admin/src/api/domain/email/types.ts
  monorepo/apps/admin/src/api/domain/step/types.ts
  monorepo/apps/admin/src/components/CardBox/CardBox.style.ts
  monorepo/apps/admin/src/components/InterviewSettingDialog/InterviewSettingDialog.style.ts
  monorepo/apps/admin/src/components/InterviewSettingDialog/InterviewSettingDialog.tsx
  monorepo/apps/admin/src/components/InterviewSettingDialog/types.ts
  monorepo/apps/admin/src/components/PlainEmailDialog/PlainEmailDialog.style.ts
  monorepo/apps/admin/src/components/PlainEmailDialog/PlainEmailDialog.tsx
  monorepo/apps/admin/src/mocks/data/step/totalSteps.json
  monorepo/apps/admin/src/pages/LoadingPage/StepManagementLoadingPage/StepManagementLoadingPage.style.ts
  monorepo/apps/admin/src/pages/StepManagementPage/StepManagementPage.tsx
  monorepo/apps/admin/src/pages/StepManagementPage/index.ts
  monorepo/apps/admin/src/router.tsx
  monorepo/apps/admin/src/utils/convertImageToBase64.ts
  monorepo/apps/admin/src/utils/index.ts
Labels: 🔨 refactor, 🚀FE

#403 [BE] 서버 500 에러 시 Discord 알림 구현
  server/src/main/java/com/ryc/api/v2/club/service/ClubService.java
  server/src/main/java/com/ryc/api/v2/common/dispatch/DiscordNotifier.java
  server/src/main/java/com/ryc/api/v2/common/dispatch/EmailSenderService.java
  server/src/main/java/com/ryc/api/v2/common/exception/GlobalExceptionHandler.java
  server/src/main/java/com/ryc/api/v2/common/exception/event/ServerErrorEvent.java
Labels: ⛑️ infra, 💻 BE

#406 [BE] club 조회 Response 빌더 누락 필드값 추가
  server/src/main/java/com/ryc/api/v2/club/service/ClubService.java
Labels: 💻 BE

#418 [FE] 공고 편집 페이지 구현 및 api 연결
  monorepo/apps/admin/package.json
  monorepo/apps/admin/src/api/domain/announcement/announcement.ts
  monorepo/apps/admin/src/api/domain/announcement/types.ts
  monorepo/apps/admin/src/assets/images/attention-triangle.svg
  monorepo/apps/admin/src/pages/AnnouncementPage/RecruitmenPage/RecruitmentPage.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/RecruitCreatePage.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/buildAnnouncementSubmitRequest.ts
  monorepo/apps/admin/src/pages/RecruitEditPage/RecruitEditPage.style.ts
  monorepo/apps/admin/src/pages/RecruitEditPage/RecruitEditPage.tsx
  monorepo/apps/admin/src/router.tsx
  monorepo/apps/user/package.json
  monorepo/yarn.lock
Labels: ⭐️ feature, 🚀FE

#420 [FE] Editor px값 변경되는 오류 수정
  monorepo/packages/ui/src/components/Editor/utils/selection.ts
Labels: 🐛 bug, 🚀FE

#424 [FE] 사이드바 드랍다운 버그 수정
  monorepo/apps/admin/src/components/SideBar/SideBar.style.tsx
  monorepo/apps/admin/src/components/SideBar/SideBar.tsx
Labels: 🐛 bug, 🚀FE

#423 [FE/REFACTOR] 관리자 페이지 UI 개선
  monorepo/apps/admin/src/components/IntervieweeCard/IntervieweeCard.style.ts
  monorepo/apps/admin/src/components/IntervieweeCard/IntervieweeCard.tsx
  monorepo/apps/admin/src/components/PersonalScoreCard/PersonalScoreCard.style.ts
  monorepo/apps/admin/src/pages/ApplicantSchedulePage/ApplicantSchedulePage.style.ts
  monorepo/apps/admin/src/pages/DocumentEvaluationPage/DocumentEvaluationPage.style.ts
  monorepo/apps/admin/src/pages/InterviewEvaluationPage/InterviewEvaluationPage.style.ts
  monorepo/apps/admin/src/pages/StepManagementPage/StepManagementPage.style.ts
  monorepo/packages/assets/images/avatarDefault.png
  monorepo/packages/ui/src/components/Avatar/Avatar.tsx
Labels: 🔨 refactor, 🚀FE

#429 ransactionalEventListener과 Transactional 혼용 버그 수정
  server/src/main/java/com/ryc/api/v2/announcement/service/AnnouncementService.java
  server/src/main/java/com/ryc/api/v2/applicant/service/ApplicantService.java
  server/src/main/java/com/ryc/api/v2/auth/service/AuthService.java
  server/src/main/java/com/ryc/api/v2/email/service/EmailService.java
  server/src/main/java/com/ryc/api/v2/evaluation/service/EvaluationService.java
  server/src/main/java/com/ryc/api/v2/interview/service/InterviewService.java
  server/src/main/java/com/ryc/api/v2/role/service/ClubRoleService.java
Labels: 🐛 bug, 💻 BE

#438 [BE/HOTFIX] 기존 리프레시 토큰 재발급시 객체 builder 사용에서 init 메소드 사용으로 수정
  server/src/main/java/com/ryc/api/v2/auth/presentation/AuthController.java
  server/src/main/java/com/ryc/api/v2/auth/service/AuthService.java
  server/src/main/java/com/ryc/api/v2/security/filter/EmailPasswordAuthenticationFilter.java
Labels: 🐛 bug, 💻 BE

#439 [FE] ErrorBoundary Fallback UI 및 ErrorDialog 구현
  monorepo/apps/admin/package.json
  monorepo/apps/admin/src/api/hooks/useEmailMutations.ts
  monorepo/apps/admin/src/components/ApplicantList/ApplicantList.style.ts
  monorepo/apps/admin/src/components/CardBox/CardBox.tsx
  monorepo/apps/admin/src/components/ErrorDialog/ErrorDialog.style.ts
  monorepo/apps/admin/src/components/ErrorDialog/ErrorDialog.tsx
  monorepo/apps/admin/src/components/ErrorDialog/index.ts
  monorepo/apps/admin/src/components/ErrorDialog/type.ts
  monorepo/apps/admin/src/components/InterviewSettingDialog/InterviewSettingDialog.tsx
  monorepo/apps/admin/src/components/InterviewSlotDropdown/InterviewSlotDropdown.tsx
  monorepo/apps/admin/src/components/PlainEmailDialog/PlainEmailDialog.tsx
  monorepo/apps/admin/src/components/index.ts
  monorepo/apps/admin/src/constants/errorText.ts
  monorepo/apps/admin/src/constants/index.ts
  monorepo/apps/admin/src/pages/ApplicantSchedulePage/ApplicantSchedulePage.style.ts
  monorepo/apps/admin/src/pages/ApplicantSchedulePage/ApplicantSchedulePage.tsx
  monorepo/apps/admin/src/pages/DocumentEvaluationPage/DocumentEvaluationPage.tsx
  monorepo/apps/admin/src/pages/ErrorFallbackPage/ErrorFallbackPage.style.ts
  monorepo/apps/admin/src/pages/ErrorFallbackPage/ErrorFallbackPage.tsx
  monorepo/apps/admin/src/pages/ErrorFallbackPage/index.ts
  monorepo/apps/admin/src/pages/ErrorFallbackPage/types.ts
  monorepo/apps/admin/src/pages/InterviewEvaluationPage/InterviewEvaluationPage.tsx
  monorepo/apps/admin/src/pages/NotFoundPage/NotFoundPage.style.ts
  monorepo/apps/admin/src/pages/NotFoundPage/NotFoundPage.tsx
  monorepo/apps/admin/src/pages/NotFoundPage/index.ts
  monorepo/apps/admin/src/pages/NotFoundPage/index.tsx
  monorepo/apps/admin/src/pages/RecruitEditPage/RecruitEditPage.style.ts
  monorepo/apps/admin/src/pages/RecruitEditPage/RecruitEditPage.tsx
  monorepo/apps/admin/src/pages/StepManagementPage/StepManagementPage.tsx
  monorepo/apps/admin/src/pages/index.ts
  monorepo/apps/admin/src/router.tsx
  monorepo/apps/user/package.json
  monorepo/apps/user/src/assets/images/attention-triangle.svg
  monorepo/apps/user/src/components/ErrorDialog/ErrorDialog.style.ts
  monorepo/apps/user/src/components/ErrorDialog/ErrorDialog.tsx
  monorepo/apps/user/src/components/ErrorDialog/index.ts
  monorepo/apps/user/src/components/ErrorDialog/type.ts
  monorepo/apps/user/src/components/index.ts
  monorepo/apps/user/src/constants/errorText.ts
  monorepo/apps/user/src/constants/index.ts
  monorepo/apps/user/src/pages/ErrorFallbackPage/ErrorFallbackPage.style.ts
  monorepo/apps/user/src/pages/ErrorFallbackPage/ErrorFallbackPage.tsx
  monorepo/apps/user/src/pages/ErrorFallbackPage/index.ts
  monorepo/apps/user/src/pages/ErrorFallbackPage/types.ts
  monorepo/apps/user/src/pages/NotFoundPage/NotFoundPage.style.ts
  monorepo/apps/user/src/pages/NotFoundPage/NotFoundPage.tsx
  monorepo/apps/user/src/pages/NotFoundPage/index.ts
  monorepo/apps/user/src/pages/NotFoundPage/index.tsx
  monorepo/apps/user/src/router.tsx
  monorepo/yarn.lock
Labels: ⭐️ feature, 🔨 refactor, 🚀FE

#437 [BE] 나의 동아리 조회 API 응답 값 수정
  server/src/main/java/com/ryc/api/v2/club/infra/projection/MyClubProjection.java
  server/src/main/java/com/ryc/api/v2/club/presentation/ClubHttpApi.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/response/MyClubGetResponse.java
  server/src/main/java/com/ryc/api/v2/club/service/ClubFacade.java
  server/src/main/java/com/ryc/api/v2/club/service/ClubService.java
  server/src/main/java/com/ryc/api/v2/club/service/dto/ClubImageDTO.java
  server/src/main/java/com/ryc/api/v2/club/service/dto/MyClubDTO.java
  server/src/main/java/com/ryc/api/v2/role/domain/ClubRoleRepository.java
  server/src/main/java/com/ryc/api/v2/role/infra/ClubRoleRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/role/infra/jpa/ClubRoleJpaRepository.java
  server/src/main/java/com/ryc/api/v2/role/service/ClubRoleService.java
Labels: ⭐️ feature, 💻 BE

#442 [FE/HOTFIX] 관리자 페이지 레이아웃 오류 수정 및 로그인 세션 관리 개선
  monorepo/.yarn/install-state.gz
  monorepo/apps/admin/src/components/SideBar/SideBar.tsx
  monorepo/apps/admin/src/layouts/ManagerLayout/ManagerLayout.style.ts
  monorepo/apps/admin/src/layouts/ManagerLayout/ManagerLayout.tsx
Labels: 🐛 bug, 🚀FE

#448 [BE/HOTFIX] 공고 업데이트시 CreatedAt Null값 입력시 도메인검증 예외 수정
  server/src/main/java/com/ryc/api/v2/announcement/domain/AnnouncementValidator.java
  server/src/main/java/com/ryc/api/v2/application/domain/ApplicationValidator.java
  server/src/main/java/com/ryc/api/v2/evaluation/domain/EvaluationValidator.java
  server/src/main/java/com/ryc/api/v2/file/domain/FileMetaDataValidator.java
Labels: 🐛 bug, 💻 BE

#453 [FE] 관리자 페이지 Editor style 적용 안되는 오류 수정
  monorepo/packages/ui/src/components/Editor/EditorTextarea.tsx
Labels: 🐛 bug, 🚀FE

#456 [BE/HOTFIX] 요청객체 검증시 400 에러 응답 검증규칙 간극 해결
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementCreateRequest.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/applicant/presentation/ApplicantHttpApi.java
  server/src/main/java/com/ryc/api/v2/application/presentation/dto/request/AnswerCreateRequest.java
  server/src/main/java/com/ryc/api/v2/applicationForm/presentation/request/QuestionCreateRequest.java
  server/src/main/java/com/ryc/api/v2/applicationForm/presentation/request/QuestionOptionCreateRequest.java
  server/src/main/java/com/ryc/api/v2/applicationForm/presentation/request/QuestionOptionUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/applicationForm/presentation/request/QuestionUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubCreateRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubSummaryRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubTagRequest.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/request/EmailSendRequest.java
  server/src/main/java/com/ryc/api/v2/evaluation/presentation/dto/request/ApplicationEvaluationRequest.java
  server/src/main/java/com/ryc/api/v2/evaluation/presentation/dto/request/EvaluationUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/evaluation/presentation/dto/request/InterviewEvaluationRequest.java
  server/src/main/java/com/ryc/api/v2/file/presentation/dto/request/UploadUrlRequest.java
  server/src/main/java/com/ryc/api/v2/interview/presentation/dto/request/NumberOfPeopleByInterviewDateRequest.java
Labels: 🐛 bug, 💻 BE

#457 [BE/HOTFIX] @NullOrNotBlank 커스텀 제거 및 기한 정보 null 허용
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementCreateRequest.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/applicant/presentation/ApplicantHttpApi.java
  server/src/main/java/com/ryc/api/v2/application/presentation/dto/request/AnswerCreateRequest.java
  server/src/main/java/com/ryc/api/v2/common/dto/request/PeriodRequest.java
  server/src/main/java/com/ryc/api/v2/common/validator/request/NullOrNotBlankValidator.java
  server/src/main/java/com/ryc/api/v2/common/validator/request/annotation/NullOrNotBlank.java
Labels: 🐛 bug, 💻 BE

#460 [BE] 이메일 인증 구현
  server/build.gradle
  server/src/main/java/com/ryc/api/ApiApplication.java
  server/src/main/java/com/ryc/api/config/SecurityConfiguration.java
  server/src/main/java/com/ryc/api/config/SwaggerConfiguration.java
  server/src/main/java/com/ryc/api/v2/admin/presentation/AdminHttpApi.java
  server/src/main/java/com/ryc/api/v2/admin/service/AdminService.java
  server/src/main/java/com/ryc/api/v2/application/presentation/ApplicationHttpApi.java
  server/src/main/java/com/ryc/api/v2/auth/presentation/AuthController.java
  server/src/main/java/com/ryc/api/v2/common/aop/annotation/VerifyEmailCode.java
  server/src/main/java/com/ryc/api/v2/common/aop/aspect/ClubRoleAspect.java
  server/src/main/java/com/ryc/api/v2/common/aop/aspect/EmailVerificationCodeAspect.java
  server/src/main/java/com/ryc/api/v2/common/constant/CustomHeaderConstant.java
  server/src/main/java/com/ryc/api/v2/common/dispatch/EmailSenderService.java
  server/src/main/java/com/ryc/api/v2/common/exception/code/EmailErrorCode.java
  server/src/main/java/com/ryc/api/v2/email/domain/Email.java
  server/src/main/java/com/ryc/api/v2/email/domain/EmailValidator.java
  server/src/main/java/com/ryc/api/v2/email/domain/EmailVerification.java
  server/src/main/java/com/ryc/api/v2/email/domain/EmailVerificationRepository.java
  server/src/main/java/com/ryc/api/v2/email/domain/enums/EmailSentStatus.java
  server/src/main/java/com/ryc/api/v2/email/infra/EmailVerificationRepositoryImpl.java
  server/src/main/java/com/ryc/api/v2/email/infra/entity/EmailEntity.java
  server/src/main/java/com/ryc/api/v2/email/infra/entity/EmailVerificationEntity.java
  server/src/main/java/com/ryc/api/v2/email/infra/jpa/EmailVerificationJpaRepository.java
  server/src/main/java/com/ryc/api/v2/email/infra/mapper/EmailVerificationMapper.java
  server/src/main/java/com/ryc/api/v2/email/presentation/EmailHttpApi.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/request/VerificationCodeCreatedRequest.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/request/VerificationCodeRequest.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/response/EmailSendResponse.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/response/VerificationCodeCreatedResponse.java
  server/src/main/java/com/ryc/api/v2/email/service/EmailService.java
  server/src/main/java/com/ryc/api/v2/email/service/EmailVerificationService.java
  server/src/main/resources/templates/email-verification.html
Labels: ⭐️ feature, 💻 BE

#466 [FE] Error UI 설정 및 버그 수정
  monorepo/apps/admin/src/api/hooks/fileMutations.ts
  monorepo/apps/admin/src/api/hooks/useEmailMutations.ts
  monorepo/apps/admin/src/api/hooks/useInterviewMutations.ts
  monorepo/apps/admin/src/components/DatePicker/DatePicker.tsx
  monorepo/apps/admin/src/components/ErrorDialog/ErrorDialog.tsx
  monorepo/apps/admin/src/components/ErrorDialog/type.ts
  monorepo/apps/admin/src/components/MainCardEditDialog/MainCardEditDialog.tsx
  monorepo/apps/admin/src/hooks/components/useEvaluation.tsx
  monorepo/apps/admin/src/hooks/useLogin.tsx
  monorepo/apps/admin/src/hooks/useQuestion.tsx
  monorepo/apps/admin/src/hooks/useRegister.tsx
  monorepo/apps/admin/src/hooks/useUpdateClub.ts
  monorepo/apps/admin/src/index.tsx
  monorepo/apps/admin/src/pages/AnnouncementPage/AnnouncementPage.tsx
  monorepo/apps/admin/src/pages/ApplicantSchedulePage/ApplicantSchedulePage.tsx
  monorepo/apps/admin/src/pages/AuthPage/LoginPage/LoginPage.tsx
  monorepo/apps/admin/src/pages/AuthPage/RegisterPage/RegisterPage.tsx
  monorepo/apps/admin/src/pages/ClubCreatePage/ClubCreatePage.tsx
  monorepo/apps/admin/src/pages/ClubEditPage/ClubEditPage.tsx
  monorepo/apps/admin/src/pages/ClubMemberRolePage/ClubMemberRolePage.tsx
  monorepo/apps/admin/src/pages/DocumentEvaluationPage/DocumentEvaluationPage.tsx
  monorepo/apps/admin/src/pages/ErrorFallbackPage/ErrorFallbackPage.tsx
  monorepo/apps/admin/src/pages/ErrorFallbackPage/types.ts
  monorepo/apps/admin/src/pages/InterviewEvaluationPage/InterviewEvaluationPage.tsx
  monorepo/apps/admin/src/pages/InviteConfirmPage/InviteConfirmPage.tsx
  monorepo/apps/admin/src/pages/NonAnnouncementPage/NonAnnouncementPage.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/DescriptionStep/DescriptionStep.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/RecruitCreatePage.tsx
  monorepo/apps/admin/src/pages/RecruitEditPage/RecruitEditPage.tsx
  monorepo/apps/admin/src/pages/StepManagementPage/StepManagementPage.tsx
  monorepo/apps/admin/src/pages/UserSettingPage/UserSettingPage.tsx
  monorepo/apps/admin/src/utils/getErrorMessage.ts
  monorepo/apps/user/src/api/hooks/clubMutation.ts
  monorepo/apps/user/src/components/ErrorDialog/ErrorDialog.tsx
  monorepo/apps/user/src/components/ErrorDialog/type.ts
  monorepo/apps/user/src/index.tsx
  monorepo/apps/user/src/pages/ClubApplyPage/ClubApplyPage.tsx
  monorepo/apps/user/src/pages/ClubDetailPage/RecruitmentPage/RecruitmentPage.tsx
  monorepo/apps/user/src/pages/ErrorFallbackPage/ErrorFallbackPage.tsx
  monorepo/apps/user/src/pages/ErrorFallbackPage/types.ts
  monorepo/apps/user/src/pages/ReservationPage/ReservationPage.tsx
  monorepo/apps/user/src/utils/getErrorMessage.ts
Labels: 🔨 refactor, 🚀FE

#470 [BE/HOTFIX] JVM 어플리케이션 한국 시간대로 강제
  server/src/main/java/com/ryc/api/ApiApplication.java
Labels: 🐛 bug, 💻 BE

#472 [FE/HOTFIX] 기한 null에 대한 처리 수정
  monorepo/apps/user/src/pages/ClubDetailPage/RecruitmentPage/RecruitmentPage.tsx
  monorepo/apps/user/src/utils/parseAnnouncementData.ts
Labels: 🐛 bug, 🚀FE

#476 [FE/Hotfix] 사이드바 관련 오류 수정
  monorepo/apps/admin/src/components/SideBar/SideBar.tsx
  monorepo/apps/admin/src/pages/AuthPage/RegisterPage/RegisterPage.tsx
  monorepo/apps/admin/src/router.tsx
Labels: 🐛 bug, 🚀FE

#481 [BE/HOTFIX] QA도중 발견한 서버 검증 버그 및 기타 버그
  server/src/main/java/com/ryc/api/v2/announcement/domain/Announcement.java
  server/src/main/java/com/ryc/api/v2/announcement/domain/AnnouncementValidator.java
  server/src/main/java/com/ryc/api/v2/announcement/domain/vo/AnnouncementPeriodInfo.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementCreateRequest.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/announcement/service/AnnouncementService.java
  server/src/main/java/com/ryc/api/v2/auth/presentation/AuthController.java
  server/src/main/java/com/ryc/api/v2/common/exception/GlobalExceptionHandler.java
  server/src/main/java/com/ryc/api/v2/common/exception/code/InvalidFormatErrorCode.java
  server/src/main/java/com/ryc/api/v2/email/domain/EmailValidator.java
  server/src/main/java/com/ryc/api/v2/email/presentation/dto/request/EmailSendRequest.java
Labels: 🐛 bug, 💻 BE

#490 [BE] 공고 상세 조회 API에 응답 값 추가
  server/src/main/java/com/ryc/api/config/SwaggerConfiguration.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/response/AnnouncementGetDetailResponse.java
Labels: ⭐️ feature, 💻 BE

#493 [BE/HOTFIX] 상시모집인 경우, 공고 진행중 상태임에 수정 안되는 사항 수정
  server/src/main/java/com/ryc/api/v2/announcement/service/AnnouncementService.java
Labels: 🐛 bug, 💻 BE

#495 [FE/HOTFIX] 지원서 동일 질문 입력 안되는 버그 수정
  monorepo/apps/user/src/pages/ClubApplyPage/ClubApplyPage.tsx
  monorepo/apps/user/src/pages/ClubApplyPage/DetailQuestionPage/ClubApplyDetailQuestionPage.tsx
Labels: 🐛 bug, 🚀FE

#498 [FE] 관리자 페이지 오류 수정 및 UI 개선
  monorepo/apps/admin/src/components/DatePicker/DatePicker.style.ts
  monorepo/apps/admin/src/components/DatePicker/DatePicker.tsx
  monorepo/apps/admin/src/components/DatePicker/types.ts
  monorepo/apps/admin/src/components/FieldLabel/FieldLabel.style.ts
  monorepo/apps/admin/src/components/FieldLabel/FieldLabel.tsx
  monorepo/apps/admin/src/components/FieldLabel/types.ts
  monorepo/apps/admin/src/components/InformationBox/InformationBox.tsx
  monorepo/apps/admin/src/components/InformationBox/types.ts
  monorepo/apps/admin/src/components/QuestionForm/QuestionForm.tsx
  monorepo/apps/admin/src/hooks/useQuestion.tsx
  monorepo/apps/admin/src/pages/AnnouncementPage/RecruitmenPage/RecruitmentPage.tsx
  monorepo/apps/admin/src/pages/DocumentEvaluationPage/DocumentEvaluationPage.tsx
  monorepo/apps/admin/src/pages/InterviewEvaluationPage/InterviewEvaluationPage.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/DescriptionStep/DescriptionStep.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/PreviewStep/PreviewStep.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/RecruitCreatePage.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/buildAnnouncementSubmitRequest.ts
  monorepo/apps/admin/src/pages/RecruitEditPage/RecruitEditPage.tsx
  monorepo/apps/user/src/assets/images/ssoc-banner.png
  monorepo/apps/user/src/pages/MainPage/MainPage.tsx
Labels: 🐛 bug, 🔨 refactor, 🚀FE

#503 [FE] 상시모집 날짜 및 다운로더 오류 수정, 비밀번호 제약 변경
  monorepo/apps/admin/src/components/DatePicker/DatePicker.tsx
  monorepo/apps/admin/src/components/FileDownloader/FileDownloader.tsx
  monorepo/apps/admin/src/pages/AuthPage/RegisterPage/RegisterPage.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/PreviewStep/PreviewStep.tsx
  monorepo/apps/admin/src/pages/RecruitCreatePage/buildAnnouncementSubmitRequest.ts
Labels: 🐛 bug, 🔨 refactor, 🚀FE

#509 [FE/HOTFIX] 사용자 권한 설정 페이지 버그 수정
  monorepo/apps/admin/src/pages/ClubMemberRolePage/ClubMemberRolePage.tsx
  monorepo/apps/user/src/pages/ClubApplyPage/ClubApplyPage.tsx
  monorepo/packages/ui/src/components/FileUpLoader/FileUpLoader.style.ts
  monorepo/packages/ui/src/components/FileUpLoader/FileUpLoaderItem.tsx
Labels: 🐛 bug, 🚀FE

#510 [FE/REFACTOR] QA 과정 발생한 필요 요구사항 수정
  monorepo/apps/admin/src/components/QuestionForm/QuestionForm.style.ts
  monorepo/apps/admin/src/components/QuestionForm/QuestionForm.tsx
  monorepo/apps/admin/src/pages/AnnouncementPage/DetailQuestionPage/DetailQuestion.style.ts
  monorepo/apps/admin/src/pages/AnnouncementPage/DetailQuestionPage/DetailQuestionPage.tsx
  monorepo/apps/admin/src/pages/AnnouncementPage/PersonalQuestionPage/PersonalQuestion.style.ts
  monorepo/apps/admin/src/pages/AnnouncementPage/PersonalQuestionPage/PersonalQuestionPage.tsx
  monorepo/apps/user/src/pages/ClubApplyPage/ClubApplyAgreemetPage/ClubApplyAgreementPage.tsx
  monorepo/apps/user/src/pages/ClubApplyPage/DetailQuestionPage/ClubApplyDetailQuestionPage.style.ts
  monorepo/apps/user/src/pages/ClubApplyPage/DetailQuestionPage/ClubApplyDetailQuestionPage.tsx
  monorepo/apps/user/src/pages/ClubApplyPage/PersonalInfoPage/ClubApplyPersonalInfoPage.style.ts
  monorepo/apps/user/src/pages/ClubApplyPage/PersonalInfoPage/ClubApplyPersonalInfoPage.tsx
  monorepo/packages/assets/images/ssoc.png
Labels: 🔨 refactor, 🚀FE

#514 [FE/HOTFIX] 면접 예약 페이지 rotuer 수정
  monorepo/apps/user/src/router.tsx
Labels: 🐛 bug, 🚀FE

#518 [FE/HOTFIX] 상시모집 날짜 이상하게 나오는 현상 해결
  monorepo/apps/admin/src/pages/AnnouncementPage/RecruitmenPage/RecruitmentPage.tsx
  monorepo/apps/admin/src/pages/RecruitEditPage/RecruitEditPage.tsx
Labels: 🐛 bug, 🚀FE

#527 [BE] 동아리 상세 설명 제한 길이 증대
  server/src/main/java/com/ryc/api/v2/announcement/domain/AnnouncementValidator.java
  server/src/main/java/com/ryc/api/v2/announcement/presentation/dto/request/AnnouncementUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/club/domain/ClubValidator.java
  server/src/main/java/com/ryc/api/v2/club/presentation/dto/request/ClubUpdateRequest.java
  server/src/main/java/com/ryc/api/v2/common/exception/code/InvalidFormatErrorCode.java
Labels: ⭐️ feature, 💻 BE

#529 [FE/HOTFIX] 프론트 버그 수정
  monorepo/apps/user/src/utils/parseAnnouncementData.ts
Labels: 🐛 bug, 🚀FE

#532 [FE] 타입 오류 해결 및 사용자 고려하여 UI 변경
  monorepo/apps/admin/src/components/CardBox/CardBox.tsx
  monorepo/apps/admin/src/components/InterviewSettingDialog/InterviewSettingDialog.tsx
  monorepo/apps/admin/src/components/InterviewSettingDialog/types.ts
  monorepo/apps/admin/src/components/InterviewTimeBox/InterviewTimeBox.style.ts
  monorepo/apps/admin/src/components/InterviewTimeBox/InterviewTimeBox.tsx
  monorepo/apps/admin/src/components/PlainEmailDialog/PlainEmailDialog.tsx
  monorepo/apps/admin/src/components/PlainEmailDialog/types.ts
  monorepo/apps/admin/src/pages/StepManagementPage/StepManagementPage.tsx
  monorepo/apps/admin/src/pages/TestPage/index.tsx
  monorepo/apps/user/src/api/domain/club/types.ts
  monorepo/apps/user/src/pages/ReservationPage/ReservationPage.tsx
Labels: 🐛 bug, ⭐️ feature, 🔨 refactor, 🚀FE

#538 [BE/HOTFIX] 면접 슬롯 생성: 2번이상 요청시 같은 시간대가 중복되어 누적되는 문제 발생
  server/src/main/java/com/ryc/api/v2/common/domain/Period.java
  server/src/main/java/com/ryc/api/v2/interview/service/InterviewService.java
Labels: 🐛 bug, 💻 BE
